version: '3'
services:
  server:
    restart: "no"
    build: ./server
    ##    working_dir: /server
    expose:
      - "8080"
    ports:
      - "8080:8080"
  client:
    restart: "no"
    build: ./client
    #    working_dir: /client
    expose:
      - "8090"
    ports:
      #      - "8080:8080"
      - "8090:8090"
    depends_on:
      - server